kind: pipeline
name: default

steps:
  - name: build-server
    image: plugins/docker
    settings:
      username: 
        from_secret: docker_username
      password: 
        from_secret: docker_password
      repo: butanediol/apptracker
      tags: dev